version: "3.9"
services:
  app:
    container_name: ${CONTAINER_BASE_NAME}_app
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - postgres
  postgres:
    container_name: ${POSTGRES_HOST}
    build: 
      dockerfile: db.Dockerfile
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    networks:
      - ${NETWORK_NAME}
  pg-admin:
    container_name: ${CONTAINER_BASE_NAME}_db_admin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    depends_on:
      - postgres
    networks:
      - ${NETWORK_NAME}
networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    name: ${NETWORK_NAME}